//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Preguntas_Cuestionario
    {
        public C_Preguntas_Cuestionario()
        {
            this.C_Respuestas_Cuestionario = new HashSet<C_Respuestas_Cuestionario>();
        }
    
        public long Corporativo { get; set; }
        public string Hotel { get; set; }
        public string Tipo_Cuestionario { get; set; }
        public int No_Pregunta { get; set; }
        public string Tipo_Pregunta { get; set; }
        public string Pregunta { get; set; }
        public string Pregunta_Ingles { get; set; }
        public int Calificacion_Maxima { get; set; }
    
        public virtual C_Tipos_Cuestionario C_Tipos_Cuestionario { get; set; }
        public virtual C_Tipos_Pregunta_Cuestionario C_Tipos_Pregunta_Cuestionario { get; set; }
        public virtual S_Hoteles S_Hoteles { get; set; }
        public virtual ICollection<C_Respuestas_Cuestionario> C_Respuestas_Cuestionario { get; set; }
    }
}
