//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class C_Respuestas_Cuestionario
    {
        public C_Respuestas_Cuestionario()
        {
            this.O_Respuestas_Cuestionario_Huespedes = new HashSet<O_Respuestas_Cuestionario_Huespedes>();
        }
    
        public long Corporativo { get; set; }
        public string Hotel { get; set; }
        public string Tipo_Cuestionario { get; set; }
        public int No_Pregunta { get; set; }
        public int No_Respuesta { get; set; }
        [Required]
        public string Respuesta { get; set; }  
        [Required]
        public string Respuesta_Ingles { get; set; }    
        public bool Respuesta_Abierta { get; set; }
    
        public virtual C_Preguntas_Cuestionario C_Preguntas_Cuestionario { get; set; }
        public virtual S_Hoteles S_Hoteles { get; set; }
        public virtual ICollection<O_Respuestas_Cuestionario_Huespedes> O_Respuestas_Cuestionario_Huespedes { get; set; }
    }
}
