//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class C_Tipos_Cuestionario
    {
        public C_Tipos_Cuestionario()
        {
            this.C_Preguntas_Cuestionario = new HashSet<C_Preguntas_Cuestionario>();
            this.S_Correos_Cuestionario = new HashSet<S_Correos_Cuestionario>();
        }
    
        public long Corporativo { get; set; }
        public string Hotel { get; set; }
        [StringLength(10)]
        public string Tipo_Cuestionario { get; set; }
        [Required]
        public string Descripcion { get; set; }
        [Required]
        public string Descripcion_Ingles { get; set; }
    
        public virtual ICollection<C_Preguntas_Cuestionario> C_Preguntas_Cuestionario { get; set; }
        public virtual S_Hoteles S_Hoteles { get; set; }
        public virtual S_Configuracion_Cuestionario S_Configuracion_Cuestionario { get; set; }
        public virtual ICollection<S_Correos_Cuestionario> S_Correos_Cuestionario { get; set; }
    }
}
