//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuestionarioEntities : DbContext
    {
        public CuestionarioEntities()
            : base("name=CuestionarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Preguntas_Cuestionario> C_Preguntas_Cuestionario { get; set; }
        public DbSet<C_Respuestas_Cuestionario> C_Respuestas_Cuestionario { get; set; }
        public DbSet<C_Tipos_Cuestionario> C_Tipos_Cuestionario { get; set; }
        public DbSet<C_Tipos_Pregunta_Cuestionario> C_Tipos_Pregunta_Cuestionario { get; set; }
        public DbSet<O_Estancias> O_Estancias { get; set; }
        public DbSet<O_Huespedes> O_Huespedes { get; set; }
        public DbSet<O_Respuestas_Cuestionario_Huespedes> O_Respuestas_Cuestionario_Huespedes { get; set; }
        public DbSet<S_Configuracion_Cuestionario> S_Configuracion_Cuestionario { get; set; }
        public DbSet<S_Corporativos> S_Corporativos { get; set; }
        public DbSet<S_Correos_Cuestionario> S_Correos_Cuestionario { get; set; }
        public DbSet<S_Hoteles> S_Hoteles { get; set; }
    }
}
