//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Huespedes
    {
        public O_Huespedes()
        {
            this.O_Estancias = new HashSet<O_Estancias>();
            this.O_Respuestas_Cuestionario_Huespedes = new HashSet<O_Respuestas_Cuestionario_Huespedes>();
        }
    
        public long Corporativo { get; set; }
        public string Hotel { get; set; }
        public string Id { get; set; }
        public long Perfil_Id { get; set; }
        public string Tipo_Reservacion { get; set; }
        public string Titulo { get; set; }
        public string Apellido { get; set; }
        public string Apellido_2 { get; set; }
        public string Nombre { get; set; }
        public string Nombre_2 { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Idioma { get; set; }
        public string Direccion { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string S_Mercado { get; set; }
        public string S_Venta { get; set; }
        public string Origen { get; set; }
        public string Medio { get; set; }
        public string Grupo { get; set; }
        public string Agencia { get; set; }
        public string Cupon { get; set; }
        public string Empresa { get; set; }
        public int Vip { get; set; }
        public Nullable<System.DateTime> Fecha_Rva { get; set; }
        public string Usuario_Captura { get; set; }
        public Nullable<System.DateTime> Fecha_Captura { get; set; }
        public string Usuario_Cancela { get; set; }
        public Nullable<System.DateTime> Fecha_Cancela { get; set; }
        public string Id_Maestro { get; set; }
        public string Forma_de_Pago { get; set; }
        public string Numero_Tarjeta { get; set; }
        public string Nombre_Tarjeta { get; set; }
        public string Expira_Tarjeta { get; set; }
        public string Detalle_Tarjeta { get; set; }
        public string Estatus { get; set; }
    
        public virtual ICollection<O_Estancias> O_Estancias { get; set; }
        public virtual S_Hoteles S_Hoteles { get; set; }
        public virtual ICollection<O_Respuestas_Cuestionario_Huespedes> O_Respuestas_Cuestionario_Huespedes { get; set; }
    }
}
