//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Corporativos
    {
        public S_Corporativos()
        {
            this.S_Hoteles = new HashSet<S_Hoteles>();
        }
    
        public long Corporativo { get; set; }
        public string Nombre_Corporativo { get; set; }
    
        public virtual ICollection<S_Hoteles> S_Hoteles { get; set; }
    }
}
