//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuestionarioWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Hoteles
    {
        public S_Hoteles()
        {
            this.C_Preguntas_Cuestionario = new HashSet<C_Preguntas_Cuestionario>();
            this.C_Respuestas_Cuestionario = new HashSet<C_Respuestas_Cuestionario>();
            this.C_Tipos_Cuestionario = new HashSet<C_Tipos_Cuestionario>();
            this.C_Tipos_Pregunta_Cuestionario = new HashSet<C_Tipos_Pregunta_Cuestionario>();
            this.O_Estancias = new HashSet<O_Estancias>();
            this.O_Huespedes = new HashSet<O_Huespedes>();
            this.O_Respuestas_Cuestionario_Huespedes = new HashSet<O_Respuestas_Cuestionario_Huespedes>();
            this.S_Configuracion_Cuestionario = new HashSet<S_Configuracion_Cuestionario>();
            this.S_Correos_Cuestionario = new HashSet<S_Correos_Cuestionario>();
        }
    
        public long Corporativo { get; set; }
        public string Hotel { get; set; }
        public string Nombre_Hotel { get; set; }
        public string RFC { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Licencia { get; set; }
    
        public virtual ICollection<C_Preguntas_Cuestionario> C_Preguntas_Cuestionario { get; set; }
        public virtual ICollection<C_Respuestas_Cuestionario> C_Respuestas_Cuestionario { get; set; }
        public virtual ICollection<C_Tipos_Cuestionario> C_Tipos_Cuestionario { get; set; }
        public virtual ICollection<C_Tipos_Pregunta_Cuestionario> C_Tipos_Pregunta_Cuestionario { get; set; }
        public virtual ICollection<O_Estancias> O_Estancias { get; set; }
        public virtual ICollection<O_Huespedes> O_Huespedes { get; set; }
        public virtual ICollection<O_Respuestas_Cuestionario_Huespedes> O_Respuestas_Cuestionario_Huespedes { get; set; }
        public virtual ICollection<S_Configuracion_Cuestionario> S_Configuracion_Cuestionario { get; set; }
        public virtual S_Corporativos S_Corporativos { get; set; }
        public virtual ICollection<S_Correos_Cuestionario> S_Correos_Cuestionario { get; set; }
    }
}
